export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const ADD_TO_CART = "ADD_TO_CART";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
